### ISSUE TITLE
CRLF not handled correctly

### ISSUE THREAD

**Issue by etet100** [junichi11/netbeans-nonewline-resolver#1]
When i'm using windows CRLF line endings a new line is inserted on each save. Could you check it?

**Comment by junichi11** [comment]
I'll try checking it later.

**Comment by junichi11** [comment]
@etet100 Could you please try 1.4.0.1-dev? : https://github.com/junichi11/netbeans-nonewline-resolver/releases/tag/v1.4.0

**Comment by etet100** [comment]
Thank you. It's perfect.

**Comment by junichi11** [comment]
Thank you for your verification :)
https://github.com/junichi11/netbeans-nonewline-resolver/releases/tag/v1.4.1 This is the same as 1.4.0.1-dev
I've also uploaded to the Maven Central.
