### ISSUE TITLE
Can't update 1.4.0 to 1.4.1

### ISSUE THREAD

**Issue by kuslja** [junichi11/netbeans-nonewline-resolver#2]
Hi,
I can't update this plugin, it seams like plugin download url is wrong, it is "https://plugins.netbeans.apache.org/catalogue/download//190/netbeans-no-newline-resolver-1.4.1.nbm",
but it should be "https://plugins.netbeans.apache.org/catalogue/download/190/netbeans-no-newline-resolver-1.4.1.nbm". 
Not sure if this is plugin or netbeans problem.
![Capture](https://user-images.githubusercontent.com/3984041/99522776-5bfbe480-2996-11eb-83e7-e5f53b7f4894.PNG)

**Comment by junichi11** [comment]
@kuslja 
Maybe, the problem is the plugin portal side, I suppose. (I can install it manually.)
Could you please report that to the NetBeans JIRA: https://issues.apache.org/jira/projects/NETBEANS/issues (Components: updatecenters - Pluignportal)?

Thanks.
