### ISSUE TITLE
[FEATURE] Don't add an empty line in empty files

### ISSUE THREAD

**Issue by terax6669** [junichi11/netbeans-nonewline-resolver#3]
Could you add this config for the plugin? It seems pointless to me to have an EOL in an empty file :)

**Comment by junichi11** [comment]
Could you please try to use version 1.4.1.1-dev? https://github.com/junichi11/netbeans-nonewline-resolver/releases/tag/v1.4.1

![netbeans-nonewline-resolver-issue3](https://user-images.githubusercontent.com/738383/128120115-3158d5e1-b6dd-4d39-b02d-4e90935176af.png)

**Comment by junichi11** [comment]
@terax6669 If there is no problem, I'll upload the new version to the PP. Thanks.

**Comment by terax6669** [comment]
I don't see any issues so far, go ahead and thanks a lot!

**Comment by junichi11** [comment]
No problem :) Thank you for your verification!
